// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: QueryDB.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertBUSDPrice = `-- name: InsertBUSDPrice :exec
INSERT INTO tblBUSDPrice ("price") VALUES ($1)
`

func (q *Queries) InsertBUSDPrice(ctx context.Context, price sql.NullString) error {
	_, err := q.db.ExecContext(ctx, insertBUSDPrice, price)
	return err
}
