apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgresdb
  labels:
    app: postgresdb
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - name: postgres-port
      port: 5432
    - name: cryptoapi-port
      port: 8888
  # Pod to route service traffic
  selector:
    app: postgresdb